"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const user_middleware_1 = require("../middlewares/user.middleware");
const user_controller_1 = require("../controllers/user.controller");
const userRoute = (0, express_1.Router)();
userRoute.post('/auth/session', user_middleware_1.userMiddleware, user_controller_1.userAuthentication);
userRoute.post('/auth/verify', user_middleware_1.userMiddleware, user_controller_1.userVerification);
userRoute.get('/task', user_middleware_1.userMiddleware, user_controller_1.userTaskList);
userRoute.post('/me', user_middleware_1.userMiddleware, user_controller_1.userInfo);
exports.default = userRoute;
